const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  //user
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //admin
  FETCH_GENDER_START: 'FETCH_GENDER_START',
  FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
  FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

  // FECTH_ROLE_SUCCESS: 'FECTH_ROLE_SUCCESS',
  // FECTH_ROLE_FAILED: 'FECTH_ROLE_FAILED',

  SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
  SAVE_USER_FAILED: 'SAVE_USER_FAILED',

  FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
  FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

  FETCH_DELETE_USERS_SUCCESS: 'FETCH_DELETE_USERS_SUCCESS',
  FETCH_DELETE_USERS_FAILED: 'FETCH_DELETE_USERS_FAILED',

  FETCH_UPDATE_USERS_SUCCESS: 'FETCH_UPDATE_USERS_SUCCESS',
  FETCH_UPDATE_USERS_FAILED: 'FETCH_UPDATE_USERS_FAILED',

  FETCH_DOCTOR_SUCCESS: 'FETCH_DOCTOR_SUCCESS',
  FETCH_DOCTOR_FAILED: 'FETCH_DOCTOR_FAILED',

  FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
  FETCH_ALL_DOCTOR_FAILED: 'FETCH_ALL_DOCTOR_FAILED',

  SAVE_DETAILS_DOCTOR_SUCCESS: 'SAVE_DETAILS_DOCTOR_SUCCESS',
  SAVE_DETAILS_DOCTOR_FAILED: 'SAVE_DETAILS_DOCTOR_FAILED',

  FETCH_ALLCODE_SCHEDULE_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_SUCCESS',
  FETCH_ALLCODE_SCHEDULE_FAILED: 'FETCH_ALLCODE_SCHEDULE_FAILED',

  FETCH_REQUIRED_DOCTOR_INFO_START: 'FETCH_REQUIRED_DOCTOR_INFO_START',
  FETCH_REQUIRED_DOCTOR_INFO_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFO_SUCCESS',
  FETCH_REQUIRED_DOCTOR_INFO_FAILED: 'FETCH_REQUIRED_DOCTOR_INFO_FAILED',
});

export default actionTypes;
